name: Demo Acciones de GitHub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permite darle clic a un botón para ejecutarlo manualmente

jobs:
  construir_y_guardar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código del repo
        uses: actions/checkout@v4

      - name: Ver qué evento lo disparó
        run: echo "Este flujo se ejecutó debido al evento -> ${{ github.event_name }}"

      - name: Crear un artefacto de prueba
        run: |
          mkdir -p artefactos_salida
          echo "Este archivo fue generado automáticamente por GitHub Actions" > artefactos_salida/resultado.txt

      - name: Subir el artefacto al almacenamiento de GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mi-artefacto-web
          path: artefactos_salida/

  probar_artefacto:
    needs: construir_y_guardar
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el artefacto en el nuevo trabajo
        uses: actions/download-artifact@v4
        with:
          name: mi-artefacto-web
          path: artefactos_salida

      - name: Leer el contenido del artefacto recibido
        run: |
          echo "Leyendo el artefacto que sobrevivió al paso anterior:"
          cat artefactos_salida/resultado.txt
